import { Injectable } from '@nestjs/common';
import type { Request, Response } from 'express';
import { AppConfig } from '../config';

/**
 * Where the refresh token lives on the wire.
 *
 * ---------------------------------------------------------------------------
 * WHY A COOKIE AND NOT THE RESPONSE BODY
 * ---------------------------------------------------------------------------
 *
 * The refresh token is the long-lived credential — thirty days, and it mints
 * access tokens. If JavaScript can read it, one XSS anywhere in the dependency
 * tree hands an attacker a month of access that survives every password change
 * short of a full revocation.
 *
 * So it is never returned in a response body and never touched by client code.
 * It is set `HttpOnly`, and the browser attaches it to the three endpoints that
 * need it. The access token stays in memory on the client, where an XSS can
 * still reach it — but that is fifteen minutes, one company and one session,
 * which is the trade this design is making deliberately.
 *
 * A page reload therefore restores the session: the client has no token, calls
 * refresh, and the cookie does the rest.
 *
 * ---------------------------------------------------------------------------
 * WHY `Path` IS THE LOAD-BEARING ATTRIBUTE
 * ---------------------------------------------------------------------------
 *
 * Scoped to the auth routes, the cookie is attached to login, refresh, logout
 * and switch-company and to nothing else. Every other endpoint in the API is
 * bearer-only and carries zero ambient authority, so the rest of the surface
 * has no CSRF exposure at all — there is nothing for a forged request to ride.
 *
 * ---------------------------------------------------------------------------
 * WHY THERE IS NO CSRF TOKEN
 * ---------------------------------------------------------------------------
 *
 * `SameSite=Lax` is not a mitigation here, it is the defence: a cross-site POST
 * does not carry the cookie at all. Lax attaches cookies to same-site requests
 * and to top-level navigations with safe methods; a form or fetch POST from
 * another site gets nothing, so the forged refresh fails before it reaches us.
 * CORS is an exact-origin allow-list, so an attacker cannot read a response
 * either.
 *
 * A double-submit token was considered and rejected. It would need to be
 * readable by JavaScript on the WEB origin while being set by the API origin —
 * which across subdomains means widening it with `Domain=.example.com` — and it
 * would have to exist before the bootstrap refresh, which by definition runs
 * when the client holds nothing. All of that to cover an attacker who already
 * controls a sibling subdomain, and who could do considerably worse with it.
 *
 * If the API is ever deployed genuinely cross-site from the web app, this
 * changes: `SameSite=None` would be required, Lax would stop protecting
 * anything, and a CSRF token becomes necessary rather than ornamental. That is
 * a deployment decision, and this comment is the note it should be read
 * against.
 *
 * NOTE ON SAME-SITE: ports are not part of a site. `localhost:3001` calling
 * `localhost:3000` is same-site, as is `app.example.com` calling
 * `api.example.com`. Different ORIGIN is not different SITE — do not reach for
 * `SameSite=None` merely because the origins differ.
 */
@Injectable()
export class SessionCookieService {
  static readonly REFRESH_COOKIE = 'undarga_rt';

  constructor(private readonly config: AppConfig) {}

  /**
   * Restricted to the auth routes, derived from the configured prefix so it
   * cannot drift out of step with the actual mount point.
   */
  private get path(): string {
    return `/${this.config.app.apiPrefix}/v1/auth`;
  }

  set(res: Response, refreshToken: string): void {
    res.cookie(SessionCookieService.REFRESH_COOKIE, refreshToken, {
      httpOnly: true,
      sameSite: 'lax',
      secure: this.config.app.isProduction,
      path: this.path,
      maxAge: this.config.auth.refreshTokenTtlDays * 86_400_000,
    });
  }

  clear(res: Response): void {
    // Attributes must match the ones it was set with, or the browser treats it
    // as a different cookie and leaves the original in place.
    res.clearCookie(SessionCookieService.REFRESH_COOKIE, {
      httpOnly: true,
      sameSite: 'lax',
      secure: this.config.app.isProduction,
      path: this.path,
    });
  }

  /**
   * Read the refresh token off the request.
   *
   * Parsed here rather than through cookie-parser: one cookie is read in one
   * place, and the middleware would put a `cookies` object on every request in
   * the application for it. The values this reads are hex generated by
   * TokenHashService, so the quoting and encoding cases a general parser
   * handles cannot arise — `decodeURIComponent` is defensive, not required.
   */
  read(req: Request): string | null {
    const header = req.headers.cookie;
    if (!header) return null;

    for (const part of header.split(';')) {
      const eq = part.indexOf('=');
      if (eq === -1) continue;

      if (part.slice(0, eq).trim() !== SessionCookieService.REFRESH_COOKIE) continue;

      const raw = part.slice(eq + 1).trim();
      if (raw === '') return null;

      try {
        return decodeURIComponent(raw);
      } catch {
        // A malformed value is an absent value, not a 500.
        return null;
      }
    }

    return null;
  }
}
