import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import undarga from '@undarga/eslint-config';

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Web lint config.
 *
 * `eslint-config-next` v16 exports flat-config arrays directly, so it is spread
 * rather than wrapped in FlatCompat — the compat shim crashes on ESLint 9.39
 * while validating Next's plugin graph.
 *
 * It also registers `@typescript-eslint` itself, and ESLint 9 refuses to let a
 * second config register the same plugin. So this file spreads Next's config
 * (which owns the plugin) and then layers on the workspace's shared RULE
 * choices from `@undarga/eslint-config`, keeping both apps to one standard
 * without a plugin collision. See packages/eslint-config/rules.js.
 */
export default [
  // A config object containing only `ignores` applies to the whole run.
  {
    ignores: [
      '.next/**',
      'next-env.d.ts',
      'coverage/**',
      // Generated by the shadcn CLI and re-generated on update. Ours to use,
      // not ours to lint.
      'components/ui/**',
      ...undarga.IGNORES,
    ],
  },

  ...nextCoreWebVitals,

  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parserOptions: { project: ['./tsconfig.json'], tsconfigRootDir: __dirname },
    },
    rules: undarga.correctnessRules,
  },

  { files: undarga.TEST_FILES, rules: undarga.testRules },
];
