import type { Metadata } from 'next';
import { AppProviders } from '@/providers';
import './globals.css';

export const metadata: Metadata = {
  title: 'Undarga — Booking Platform',
  description: 'Multi-tenant booking platform for companies with multiple branches.',
};

/**
 * Root layout — a Server Component.
 *
 * `LayoutProps<'/'>` is generated by Next 16 from the route tree (run
 * `next typegen`); it replaces hand-writing `{ children: React.ReactNode }` and
 * stays correct when the route gains parameters.
 *
 * Only <AppProviders> is a client boundary, so everything outside it stays on
 * the server.
 *
 * Fonts come from the system stack defined in globals.css rather than
 * next/font/google — see the note there.
 */
export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="bg-background text-foreground min-h-full">
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
